### ISSUE TITLE
Question: myImportFields

### ISSUE THREAD

**Issue by mreid2005** [sayuga/SerenityTutorials#3]
in  your tutorial you specify that myImportFields.cs is general file able to be used for multiple modules.

but under multiValJoin AddressLogRow is referenced along with CustomerId which seems specific to a specific Table in the Northwind Sample.

myModule is named Inventory. I have multiple tables that I need to create separate imports for, that have different requirements for each table being imported.

assets_master primary key is 'id'

How would this be done using myImportfields.cs as a "general" file?

also, Where did AddressLogRow come from? is that a required dependancy. or unique to myModule/myTable?

**Comment by sayuga** [comment]
I'll gladly explain.  The multiValJoin you see is a sample handler using a table AddressLogRow joined to the table you are importing to by having the CustomerId being the ForeignKey passed back to the table you're importing to. . 

Here is the breakdown borrowing from your module name: 

If, like in the case of cascaded values, you need to validate that a relation exists between multiple fields, if the Joint field happens to have a combination of multiple fields needing validation, you need to match every field so that the cascade relationship is consistent. If the combination of fields doesn't exist already , you need to create the new combination. 

Since you are, after all, looking for the ID of the table you join to and then passing it to the field in the table you are importing to, the criteria of what fields need to be match can be unique depending on how you join the table. This is why we do the handler in a general format so that we can use it when importing into other tables if neccesary (Not generics, general. I'm currently not that versed on generics) 

Thought Structure: Table you are working in <-Joins-> Inventory Table where a combination of fields match. If no match, create and get newId for table you are working on. 


public static Int32 inventoryImportCase(IDbConnection myConnection, List<String> myErrors, int row, List<string>expectedHeader, List<dynamic> val)
        {
            //I assign the values I'm importing to a array for specific use in this event. 

            string[] wsField = new string[] { Convert.ToString(val[0]), Convert.ToString(val[1]) };            
            var g = InventoryRow.Fields; //I tell it what table fields I'm going to reference and check off of

            //check the Inventory table to see if the combination of firstField with otherField already exists. If it exists, it takes the existing inventoryId for that row. 
            var currRow = myConnection.TryFirst<InventoryRow => q.Select(g.InventoryId).Where(g.FirstField == wsField[0] & g.OtherField== wsField[1])); 

            if (currRow == null) //if that specific fields combination did not exist. 
            {
                try
                {
                    var newRow = myConnection.InsertAndGetID(new InventoryRow { Floor = wsField[0], Room = wsField[1] }); //create new entry with that specific combination of fields.                                 
                    return Convert.ToInt32(newRow); //take the id of the new row to pass it to the table you're joining to. 
                }
                catch (IOException e)
                {
                    myErrors.Add("IOException for Fields " + expectedHeader[0]+" and "+ expectedHeader[1] + "  on row " + row + " : " + e.Message); //if something went wrong it tells you.                     
                }
            }
            return currRow.InventoryId.Value; //If the row did exist with the combination of fields, it takes the inventory id and passes it back. 
}

Since we identified that these are the criteria for checking which item is being imported, you can then reuse on any other table you are importing to that may need to import from this table. I tend to create one of these for each table I have that will be used for joining to other tables.

**Comment by mreid2005** [comment]
Great Explanation thank you!
